config/routes.rb
Rails.application.routes.draw do
  resources :airports
  root 'airports#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airport.rb
class Airport < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  before_action :set_airport, only: [:show, :edit, :update, :destroy]

  # GET /airports
  # GET /airports.json
  def index
    @airports = Airport.all.paginate page: params[:page], per_page: 10
  end

  # GET /airports/1
  # GET /airports/1.json
  def show
  end

  # GET /airports/new
  def new
    @airport = Airport.new
  end

  # GET /airports/1/edit
  def edit
  end

  # POST /airports
  # POST /airports.json
  def create
    @airport = Airport.new(airport_params)

    respond_to do |format|
      if @airport.save
        format.html { redirect_to @airport, notice: 'Airport was successfully created.' }
        format.json { render :show, status: :created, location: @airport }
      else
        format.html { render :new }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airports/1
  # PATCH/PUT /airports/1.json
  def update
    respond_to do |format|
      if @airport.update(airport_params)
        format.html { redirect_to @airport, notice: 'Airport was successfully updated.' }
        format.json { render :show, status: :ok, location: @airport }
      else
        format.html { render :edit }
        format.json { render json: @airport.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airports/1
  # DELETE /airports/1.json
  def destroy
    @airport.destroy
    respond_to do |format|
      format.html { redirect_to airports_url, notice: 'Airport was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airport
      @airport = Airport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airport_params
      params.require(:airport).permit(:iata, :iso, :name, :airport_type, :size, :longitude, :latitude)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/airports/_form.html.haml
= form_with(model: airport, local: true) do |form|
  - if airport.errors.any?
    #error_explanation
      %h2
        = pluralize(airport.errors.count, "error")
        prohibited this airport from being saved:
      %ul
        - airport.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :iata
    = form.text_field :iata, id: :airport_iata
  .field
    = form.label :iso
    = form.text_field :iso, id: :airport_iso
  .field
    = form.label :name
    = form.text_field :name, id: :airport_name
  .field
    = form.label :type
    = form.text_field :type, id: :airport_type
  .field
    = form.label :size
    = form.text_field :size, id: :airport_size
  .field
    = form.label :longitude
    = form.text_field :longitude, id: :airport_longitude
  .field
    = form.label :latitude
    = form.text_field :latitude, id: :airport_latitude
  .actions
    = form.submit

app/views/airports/_rows.html.haml
.text-center 
  = will_paginate airports, renderer: RemoteLinkPagination::LinkRenderer
    
%table.table.table-bordered
  %thead.thead-dark
    %tr
    %th Iata
    %th Iso
    %th Name
    %th Type
    %th Size
    %th Longitude
    %th Latitude
    %th{colspan: "3"} Actions
  %tbody
    - airports.each do |airport|  
      %tr
        %td= airport.iata
        %td= airport.iso
        %td= airport.name
        %td= airport.airport_type
        %td= airport.size
        %td= airport.longitude
        %td= airport.latitude
        %td= link_to 'Show', airport, class: "btn btn-primary"
        %td= link_to 'Edit', edit_airport_path(airport), class: "btn btn-warning"
        %td= link_to 'Destroy', airport, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

app/views/airports/edit.html.haml
%h1 Editing Airport

= render 'form', airport: @airport

= link_to 'Show', @airport |
= link_to 'Back', airports_path

app/views/airports/index.html.haml
.container
  %p#notice= notice
  %h1 Airports
  #rows
    = render 'rows', airports: @airports
  %br/
  = link_to 'New Airport', new_airport_path

app/views/airports/new.html.haml
%h1 New Airport

= render 'form', airport: @airport
= link_to 'Back', airports_path    

app/views/airports/show.html.haml
%p#notice= notice

%p
  %strong Iata:
  = @airport.iata  
%p
  %strong Iso:
  = @airport.iso    
%p
  %strong Name:
  = @airport.name
%p
  %strong Type:
  = @airport.airport_type
%p
  %strong Size:
  = @airport.size
%p
  %strong Longitude:
  = @airport.longitude
%p
  %strong Latitude:
  = @airport.latitude

= link_to 'Edit', edit_airport_path(@airport) |
= link_to 'Back', airports_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TutorialWillPaginate</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>